# Generated by Django 4.0.7 on 2022-09-11 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_after_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount',
            field=models.CharField(choices=[('No Discound', 'No Discound'), ('10 % Discount', '10 % Discount'), ('20 % Discount', '20 % Discount'), ('30 % Discount', '30 % Discount'), ('40 % Discount', '40 % Discount'), ('50 % Discount', '50 % Discount')], default=('No Discound', 'No Discound'), max_length=50),
        ),
    ]
