# Generated by Django 4.0.7 on 2022-10-06 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_color_color_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email',
            field=models.EmailField(default='test@gmail.com', max_length=100, unique=True),
        ),
    ]
