# Generated by Django 4.0.7 on 2022-09-12 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_order_order_status_alter_order_total'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'الاصناف', 'verbose_name_plural': 'الاصناف'},
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'المستخدمين', 'verbose_name_plural': 'المستخدمين'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'الطلبات', 'verbose_name_plural': 'الطلبات'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'المنتجات', 'verbose_name_plural': 'المنتجات'},
        ),
    ]
