# Generated by Django 4.0.7 on 2022-10-19 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_customuser_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('colors', models.ManyToManyField(blank=True, to='api.color')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product')),
                ('sizes', models.ManyToManyField(blank=True, to='api.size')),
            ],
        ),
    ]
