# Generated by Django 4.0.7 on 2022-10-20 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_order_ordered_by_order_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart',
        ),
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('sizes', models.CharField(blank=True, max_length=200, null=True)),
                ('colors', models.CharField(blank=True, max_length=200, null=True)),
                ('quantity_ordered', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, default=99.99, max_digits=15)),
                ('selling_price', models.DecimalField(decimal_places=2, default=99.99, max_digits=15)),
                ('shop', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(to='api.productorder'),
        ),
    ]
