# Generated by Django 4.0.7 on 2022-10-20 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_order_cart_productorder_alter_order_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartproduct',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartproduct',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productitems',
            name='colors',
        ),
        migrations.RemoveField(
            model_name='productitems',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productitems',
            name='sizes',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartProduct',
        ),
        migrations.DeleteModel(
            name='ProductItems',
        ),
    ]
