# Generated by Django 4.0.7 on 2022-10-21 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_order_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='size_name',
            field=models.CharField(max_length=4),
        ),
    ]
