# Generated by Django 4.0.7 on 2022-10-25 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_customuser_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='state',
            field=models.CharField(blank=True, choices=[('بغداد', 'بغداد'), ('الانبار', 'الانبار'), ('بابل', 'بابل'), ('بصرة', 'بصرة'), ('ذي قار', 'ذي قار'), ('ديالى', 'ديالى'), ('دهوك', 'دهوك'), ('اربيل', 'اربيل'), ('كربلاء', 'كربلاء'), ('كركوك', 'كركوك'), ('ميسان', 'ميسان'), ('المثنى', 'المثنى'), ('النجف', 'النجف'), ('الموصل', 'الموصل'), ('صلاح الدين', 'صلاح الدين'), ('سليمانية', 'سليمانية'), ('واسط', 'واسط')], default=('بغداد', 'بغداد'), max_length=20, null=True),
        ),
    ]
