# Generated by Django 4.0.7 on 2022-10-31 15:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_customuser_options_remove_customuser_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
