# Generated by Django 4.0.7 on 2022-11-02 17:31

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_product_diffrenece'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(upload_to='products/%Y/%m/%d/', validators=[api.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo_1',
            field=models.FileField(blank=True, upload_to='products/%Y/%m/%d/', validators=[api.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo_10',
            field=models.FileField(blank=True, upload_to='products/%Y/%m/%d/', validators=[api.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo_2',
            field=models.FileField(blank=True, upload_to='products/%Y/%m/%d/', validators=[api.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo_3',
            field=models.FileField(blank=True, upload_to='products/%Y/%m/%d/', validators=[api.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo_4',
            field=models.FileField(blank=True, upload_to='products/%Y/%m/%d/', validators=[api.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo_5',
            field=models.FileField(blank=True, upload_to='products/%Y/%m/%d/', validators=[api.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo_6',
            field=models.FileField(blank=True, upload_to='products/%Y/%m/%d/', validators=[api.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo_7',
            field=models.FileField(blank=True, upload_to='products/%Y/%m/%d/', validators=[api.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo_8',
            field=models.FileField(blank=True, upload_to='products/%Y/%m/%d/', validators=[api.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo_9',
            field=models.FileField(blank=True, upload_to='products/%Y/%m/%d/', validators=[api.validators.validate_file_size]),
        ),
    ]
