# Generated by Django 4.0.7 on 2022-11-05 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_product_image_alter_product_photo_1_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'المستخدم', 'verbose_name_plural': 'المستخدمين'},
        ),
        migrations.AlterField(
            model_name='color',
            name='color_name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Order Received', 'تم وصول الطلب'), ('Order Processing', 'Order Processing'), ('on the way', 'on the way'), ('Order Complated', 'Order Complated'), ('Order Canceled', 'Order Canceled')], default=('Order Received', 'تم وصول الطلب'), max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(blank=True, to='api.productorder'),
        ),
        migrations.AlterField(
            model_name='size',
            name='size_name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
