# Generated by Django 4.0.7 on 2022-11-05 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_customuser_options_alter_color_color_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='discount',
            field=models.CharField(choices=[('No Discound', 'بلا تخفيض'), ('5 % Discount', '5% تخفيض'), ('10 % Discount', '10% تخفيض'), ('20 % Discount', '20% تخفيض'), ('30 % Discount', '30% تخفيض'), ('40 % Discount', '40% تخفيض'), ('50 % Discount', '50% تخفيض')], default=('No Discound', 'بلا تخفيض'), max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Order Received', 'تم وصول الطلب'), ('Order Processing', 'جاري تحضير الطلب'), ('on the way', 'الطلب في الطريق'), ('Order Complated', 'اكتمل الطلب'), ('Order Canceled', 'تم إلغاء الطلب')], default=('Order Received', 'تم وصول الطلب'), max_length=50),
        ),
    ]
